### PR TITLE
PHP 8.3 support

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Actions seem to have broken 3 months ago? I think they need re-enabling?

**Comment by mnapoli** [comment]
Oh yeah good point. Weird, they were enabled, just disabling + re-enabling seemed to do the trick.

**Comment by GrahamCampbell** [comment]
I think it's due to the cron you have. GitHub turn off actions for repos with crons but no commit activity.

**Comment by mnapoli** [comment]
Oh I didn't know it would also disable regular actions! I thought only the cron would be disabled.

**Comment by GrahamCampbell** [comment]
Yeh, I think they just have a big hammer. :P

**Pull request merged**
